android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Fill these in after creating/opening your Supabase project.
MYVAULT_SUPABASE_URL=https://wrfhfrrcgzedsnfsmsrd.supabase.co
MYVAULT_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZmhmcnJjZ3plZHNuZnNtc3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NTg0NjcsImV4cCI6MjA5MzEzNDQ2N30.pXXWebYwjCybY7CfzBLbFBu7gaTf0uQrRFdBxdpGIYU
MYVAULT_SYNC_PROXY_URL=
MYVAULT_SYNC_PROXY_TOKEN=
