package com.myvault.app.data.repository

import com.myvault.app.data.local.dao.AiConversationDao
import com.myvault.app.data.local.entity.AiConversationEntity
import com.myvault.app.data.local.entity.AiMessageEntity
import com.myvault.app.ui.viewmodel.NoteAiChatMessage
import com.myvault.app.ui.viewmodel.NoteAiMessageRole
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

data class AiConversationSession(
    val id: String,
    val messages: List<NoteAiChatMessage>,
)

data class AiConversationSummary(
    val id: String,
    val noteId: String,
    val title: String,
    val preview: String,
    val messageCount: Int,
    val updatedAt: Long,
)

@Singleton
class AiConversationRepository @Inject constructor(
    private val dao: AiConversationDao,
) {
    suspend fun loadLatestSession(noteId: String): AiConversationSession? {
        val conversation = dao.latestConversationForNote(noteId) ?: return null
        return AiConversationSession(
            id = conversation.id,
            messages = dao.messagesForConversation(conversation.id).mapNotNull { it.toUiMessage() },
        )
    }

    suspend fun loadMessages(conversationId: String): List<NoteAiChatMessage> =
        dao.messagesForConversation(conversationId).mapNotNull { it.toUiMessage() }

    suspend fun conversationSummaries(noteId: String): List<AiConversationSummary> =
        dao.conversationsForNote(noteId).map { conversation ->
            val messages = dao.messagesForConversation(conversation.id).mapNotNull { it.toUiMessage() }
            AiConversationSummary(
                id = conversation.id,
                noteId = conversation.noteId,
                title = conversation.title.takeUnless { it.isBlank() || it == "Ask AI" }
                    ?: messages.firstOrNull { it.role == NoteAiMessageRole.User }?.content?.toConversationTitle()
                    ?: "Ask AI",
                preview = messages.firstOrNull { it.role == NoteAiMessageRole.User }?.content?.toConversationPreview()
                    ?: messages.firstOrNull()?.content?.toConversationPreview()
                    ?: "No messages yet",
                messageCount = messages.size,
                updatedAt = conversation.updatedAt,
            )
        }

    suspend fun saveMessage(message: NoteAiChatMessage, conversationId: String? = null): String {
        val conversation = ensureConversation(message.noteId, conversationId, message)
        dao.upsertMessage(message.toEntity(conversation.id))
        dao.upsertConversation(
            conversation.copy(
                title = if (conversation.title in AutoGeneratedConversationTitles && message.role == NoteAiMessageRole.User) {
                    message.content.toConversationTitle()
                } else {
                    conversation.title
                },
                updatedAt = System.currentTimeMillis(),
            ),
        )
        return conversation.id
    }

    suspend fun startConversation(noteId: String): String {
        val now = System.currentTimeMillis()
        val conversation = AiConversationEntity(
            id = UUID.randomUUID().toString(),
            noteId = noteId,
            title = "New chat",
            createdAt = now,
            updatedAt = now,
        )
        dao.upsertConversation(conversation)
        return conversation.id
    }

    suspend fun clearConversation(conversationId: String) {
        dao.deleteMessagesForConversation(conversationId)
        dao.deleteConversation(conversationId)
    }

    suspend fun clearNoteConversation(noteId: String) {
        dao.deleteMessagesForNote(noteId)
        dao.deleteConversationsForNote(noteId)
    }

    private suspend fun ensureConversation(
        noteId: String,
        conversationId: String?,
        seedMessage: NoteAiChatMessage,
    ): AiConversationEntity {
        if (conversationId != null) {
            dao.conversationById(conversationId)?.let { return it }
        }
        val existing = dao.latestConversationForNote(noteId)
        if (existing != null && dao.messagesForConversation(existing.id).isEmpty()) return existing
        val now = System.currentTimeMillis()
        return AiConversationEntity(
            id = UUID.randomUUID().toString(),
            noteId = noteId,
            title = if (seedMessage.role == NoteAiMessageRole.User) seedMessage.content.toConversationTitle() else "Ask AI",
            createdAt = now,
            updatedAt = now,
        ).also { dao.upsertConversation(it) }
    }
}

private fun AiMessageEntity.toUiMessage(): NoteAiChatMessage? {
    val roleValue = runCatching { NoteAiMessageRole.valueOf(role) }.getOrNull() ?: return null
    return NoteAiChatMessage(
        id = id,
        noteId = noteId,
        role = roleValue,
        content = content,
        timestamp = createdAt,
        action = action?.let { runCatching { NoteAiAction.valueOf(it) }.getOrNull() },
        provider = provider?.let { runCatching { NoteAiProvider.valueOf(it) }.getOrNull() },
        model = model?.let { runCatching { NoteAiModel.valueOf(it) }.getOrNull() },
    )
}

private fun NoteAiChatMessage.toEntity(conversationId: String): AiMessageEntity =
    AiMessageEntity(
        id = id,
        conversationId = conversationId,
        noteId = noteId,
        role = role.name,
        content = content,
        action = action?.name,
        provider = provider?.name,
        model = model?.name,
        selectedTextContext = null,
        createdAt = timestamp,
)

private val AutoGeneratedConversationTitles = setOf("Ask AI", "New chat")

private fun String.toConversationTitle(): String =
    lineSequence()
        .map { it.trim() }
        .firstOrNull { it.isNotBlank() }
        ?.replace(Regex("\\s+"), " ")
        ?.take(44)
        ?.trim()
        ?.ifBlank { null }
        ?: "Ask AI"

private fun String.toConversationPreview(): String =
    replace(Regex("\\s+"), " ")
        .trim()
        .take(96)
        .ifBlank { "No preview" }
